export const COUNTER_INCREMENT = Symbol('COUNTER_INCREMENT');
export const COUNTER_DECREMENT = Symbol('COUNTER_DECREMENT');

export const POSTS_FETCH_START = Symbol('POSTS_FETCH_START');
export const POSTS_FETCH_SUCCESS = Symbol('POSTS_FETCH_SUCCESS');
export const POSTS_FETCH_FAILURE = Symbol('POSTS_FETCH_FAILURE');
